# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('area', models.DecimalField(decimal_places=20, max_digits=35)),
            ],
            options={
                'ordering': ('latitude', 'longitude'),
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['state', 'district'],
            },
        ),
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('area', models.DecimalField(decimal_places=20, max_digits=35)),
            ],
            options={
                'ordering': ('latitude', 'longitude'),
            },
        ),
        migrations.CreateModel(
            name='LandfillConceptualModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='LandfillForm1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s0', models.TextField(default='')),
                ('s1', models.TextField(default='')),
                ('s2', models.TextField(default='')),
                ('s3', models.TextField(default='')),
                ('s4', models.TextField(default='')),
                ('s5', models.TextField(default='')),
                ('s6', models.TextField(default='')),
                ('s7', models.TextField(default='')),
                ('s8', models.TextField(default='')),
                ('s9', models.TextField(default='')),
                ('s10', models.TextField(default='')),
                ('s11', models.TextField(default='')),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='LandfillForm4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s0', models.TextField(default='')),
                ('s1', models.TextField(default='')),
                ('s2', models.TextField(default='')),
                ('s3', models.TextField(default='')),
                ('s4', models.TextField(default='')),
                ('s5', models.TextField(default='')),
                ('s6', models.TextField(default='')),
                ('s7', models.TextField(default='')),
                ('s8', models.TextField(default='')),
                ('s9', models.TextField(default='')),
                ('s10', models.TextField(default='')),
                ('s11', models.TextField(default='')),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='LandfillProtocolComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='Landfills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('area', models.DecimalField(decimal_places=20, max_digits=35)),
                ('distance_airport', models.DecimalField(decimal_places=20, max_digits=35)),
                ('distance_water', models.DecimalField(decimal_places=20, max_digits=35)),
                ('distance_well', models.DecimalField(decimal_places=20, max_digits=35)),
                ('distance_road', models.DecimalField(decimal_places=20, max_digits=35)),
                ('distance_river', models.DecimalField(decimal_places=20, max_digits=35)),
                ('road_name', models.CharField(max_length=1000)),
                ('airport_name', models.CharField(max_length=1000)),
                ('river_name', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfills', to='gMapsIntegration.Districts')),
            ],
            options={
                'ordering': ('latitude', 'longitude'),
            },
        ),
        migrations.CreateModel(
            name='LandfillSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.IntegerField()),
                ('index', models.IntegerField()),
                ('completed', models.IntegerField(default=0)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_sample', to='gMapsIntegration.Landfills')),
            ],
            options={
                'ordering': ['sample_type', 'index', 'landfill'],
            },
        ),
        migrations.CreateModel(
            name='LandfillSampleComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.IntegerField()),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_sample_comments', to='gMapsIntegration.Landfills')),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='LandfillSampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('data', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('landfill_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_sample_data', to='gMapsIntegration.LandfillSample')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='LandfillsExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_water', models.DecimalField(decimal_places=20, default=10000, max_digits=35)),
                ('depth_waste', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('area', models.DecimalField(decimal_places=20, default=0, max_digits=35)),
                ('groundwater_depth', models.DecimalField(decimal_places=4, default=100, max_digits=14)),
                ('soil_perm', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('groundwater_quality', models.IntegerField(default=0)),
                ('distance_habitat', models.DecimalField(decimal_places=20, default=100, max_digits=35)),
                ('distance_airport', models.DecimalField(decimal_places=20, default=100, max_digits=35)),
                ('distance_water_body', models.DecimalField(decimal_places=20, default=10000, max_digits=35)),
                ('type_soil', models.DecimalField(decimal_places=4, default=100, max_digits=14)),
                ('life_future', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('waste_type', models.IntegerField(default=0)),
                ('waste_quantity_site', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('waste_quantity_disposed', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('distance_village', models.DecimalField(decimal_places=20, default=10000, max_digits=35)),
                ('flood', models.DecimalField(decimal_places=4, default=1000, max_digits=14)),
                ('rainfall_annual', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('distance_city', models.DecimalField(decimal_places=20, default=100, max_digits=35)),
                ('public_acceptance', models.IntegerField(default=0)),
                ('ambient_air', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('waste_hazard', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('biodegradable_waste', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('age_filing', models.DecimalField(decimal_places=4, default=100, max_digits=14)),
                ('waste_moisture', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('bod', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cod', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tds', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_extra', to='gMapsIntegration.Landfills')),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='LandfillsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='landfills/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gMapsIntegration.Landfills')),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('area', models.DecimalField(decimal_places=20, max_digits=35)),
            ],
            options={
                'ordering': ('latitude', 'longitude'),
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('area', models.DecimalField(decimal_places=20, max_digits=35)),
            ],
            options={
                'ordering': ('latitude', 'longitude'),
            },
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('area', models.DecimalField(decimal_places=20, max_digits=35)),
            ],
            options={
                'ordering': ('latitude', 'longitude'),
            },
        ),
        migrations.AddField(
            model_name='landfillprotocolcomments',
            name='landfill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_protocol_comments', to='gMapsIntegration.Landfills'),
        ),
        migrations.AddField(
            model_name='landfillform4',
            name='landfill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_form4', to='gMapsIntegration.Landfills'),
        ),
        migrations.AddField(
            model_name='landfillform1',
            name='landfill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_form1', to='gMapsIntegration.Landfills'),
        ),
        migrations.AddField(
            model_name='landfillconceptualmodel',
            name='landfill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_conceptual_model', to='gMapsIntegration.Landfills'),
        ),
        migrations.AddField(
            model_name='districts',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='gMapsIntegration.States'),
        ),
    ]
