# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gMapsIntegration', '0002_landfillsfinalsiteconceptualmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandfillsBaselineDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.TextField(default='')),
                ('x1', models.TextField(default='')),
                ('x2', models.TextField(default='')),
                ('x3', models.TextField(default='')),
                ('x4', models.TextField(default='')),
                ('x5', models.TextField(default='')),
                ('x6', models.TextField(default='')),
                ('x7', models.TextField(default='')),
                ('x8', models.TextField(default='')),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landfill_baseline_data', to='gMapsIntegration.Landfills')),
            ],
            options={
                'ordering': ['landfill'],
            },
        ),
    ]
